name: Integración continua

on:
  push:
    paths:
      - realworld.yml

jobs:
    spectral:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Instalar Node.js y npm
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Instalar Spectral
              run: npm install -g @stoplight/spectral-cli
            - name: Validar con Spectral
              run: spectral lint --fail-severity warn realworld.yml
    copiar-a-repo-api-client:
        runs-on: ubuntu-latest
        needs: spectral
        steps:
          - name: Clonar el repositorio
            uses: actions/checkout@v4
          - name: Clonar repositorio de api-client
            uses: actions/checkout@v4
            with:
              repository: AntarEspadas/openapi-generator-ts-test
              ref: master
              path: ./api-client
              ssh-key: ${{ secrets.SSH_KEY }}
          - name: Copiar especificación
            run: cp realworld.yml ./api-client/realworld.yml
          - name: Configurar git
            run: |
              git config user.name "github-actions"
              git config user.email "github-actions@github.com"
            working-directory: ./api-client
          - name: Crear y subir commit
            run: |
              git commit -m "Actualizar especificación de OpenAPI"
              git push
            working-directory: ./api-client