name: Integración continua

on: push

jobs:
    spectral:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Instalar Node.js y npm
              uses: actions/setup-node@v4
              with:
                node-version: 21
            - name: Instalar Spectral
              run: npm install -g @stoplight/spectral-cli
            - name: Validar con Spectral
              run: spectral lint --fail-severity warn realworld.yml
